gembaadvantage/uplift

.github/workflows/release.yml
.goreleaser.yml

ci(release): update workflow to sign checksum file

---

.goreleaser.yml
cmd/uplift/bump.go
cmd/uplift/completion.go
cmd/uplift/root.go

feat: support shell completion 

---

.github/workflows/ci.yml
README.md
internal/config/uplift.go
internal/git/utils.go
internal/git/utils_test.go
internal/semver/bump.go
internal/semver/bump_test.go

feat: support creation of annotated tags (#25)

---

.github/workflows/release.yml
.goreleaser.yml

ci: support publishing to snapcraft

---

README.md
cmd/uplift/release.go
cmd/uplift/root.go
cmd/uplift/tag.go
internal/context/context.go
internal/task/gitpush/gitpush.go
internal/task/gitpush/gitpush_test.go
internal/task/gittag/gittag.go
internal/task/gittag/gittag_test.go

feat: skip commit and push through global flag

---

README.md
cmd/uplift/root.go

feat: add support for discarding all logging

---

README.md
cmd/uplift/bump.go
cmd/uplift/changelog.go
cmd/uplift/completion.go
cmd/uplift/main.go
cmd/uplift/release.go
cmd/uplift/root.go
cmd/uplift/tag.go
cmd/uplift/version.go
internal/context/context.go
internal/task/gittag/gittag.go
internal/task/gittag/gittag_test.go

feat: output next tag without tagging repository

---

README.md
cmd/uplift/release.go

feat: add support for checking if a release will be triggered ahead of time

---

README.md
cmd/uplift/changelog.go
internal/context/context.go
internal/task/changelog/changelog.go
internal/task/changelog/changelog_test.go
internal/task/changelog/template/diff.tpl

feat: support output of changelog diff only

---

internal/task/changelog/changelog_test.go
internal/task/changelog/template/new.tpl

fix: better align changelog template to keep a changelog

---

cmd/uplift/release.go

fix: align release check command output with other commands

---

internal/semver/version.go
internal/task/bump/bump.go
internal/task/nextcommit/nextcommit.go
internal/task/nextcommit/nextcommit_test.go

fix: support version token in custom commit message

---

README.md
cmd/uplift/changelog.go
cmd/uplift/changelog_test.go
internal/config/uplift.go
internal/context/context.go
internal/git/utils.go
internal/git/utils_test.go
internal/task/changelog/changelog.go
internal/task/changelog/changelog_test.go

feat: add option to filter commits by prefix from changelog

---

CONTRIBUTING.md

chore: add a pull request contributing guide

---

internal/task/changelog/changelog_test.go
internal/task/changelog/template/append.tmpl
internal/task/changelog/template/diff.tmpl
internal/task/changelog/template/new.tmpl

fix: use bulleted list with changelog commits

---

README.md
cmd/uplift/changelog.go
cmd/uplift/changelog_test.go
cmd/uplift/release_test.go
cmd/uplift/tag_test.go
internal/context/context.go
internal/git/utils.go
internal/git/utils_test.go
internal/task/changelog/changelog.go
internal/task/changelog/changelog_test.go
internal/task/changelog/template/append.tmpl
internal/task/changelog/template/diff.tmpl
internal/task/changelog/template/new.tmpl
internal/task/currentversion/currentversion.go
internal/task/gittag/gittag_test.go

feat: support creation of a full changelog

---

.goreleaser.yml

ci: goreleaser to manage release of gofish fish food

---

README.md
cmd/uplift/changelog.go
cmd/uplift/changelog_test.go
internal/config/uplift.go
internal/context/context.go
internal/task/changelog/changelog.go
internal/task/changelog/changelog_test.go

feat: optional sorting of commits within changelog

---

.github/workflows/ci.yml
README.md
cmd/uplift/release.go
cmd/uplift/release_test.go
internal/context/context.go
internal/git/utils.go
internal/git/utils_test.go
internal/task/changelog/changelog.go

feat: enable changelog creation during release

---

README.md
cmd/uplift/changelog.go
cmd/uplift/changelog_test.go
cmd/uplift/release.go
internal/context/context.go
internal/task/changelog/changelog.go
internal/task/changelog/changelog_test.go

feat: exclude auto-generated uplift commits from changelog

---

.github/workflows/ci.yml
README.md
cmd/uplift/release.go
cmd/uplift/release_test.go
internal/context/context.go
internal/task/bump/bump.go
internal/task/changelog/changelog.go

feat: add flags to optionally skip stages within the release workflow

---

README.md
go.mod
go.sum
internal/config/uplift.go
internal/task/bump/bump.go
internal/task/bump/bump_test.go
internal/task/bump/json.go
internal/task/bump/json_test.go
internal/task/bump/regex_test.go

feat: support file bumping using json paths

---

cmd/uplift/changelog.go
internal/git/utils.go

fix: include scm detection with changelog diff

---

cmd/uplift/changelog.go

fix: ignore case on sort order within config

---

.github/workflows/ci.yml
.goreleaser.yml

feat: enable signing of all artifacts using cosign

---

docs/content/install.md

docs: add instructions on running uplift locally using docker

---

.goreleaser.yml

feat: support creation of dedicated arm64 docker images

---

Dockerfile

fix: copy uplift into path within dockerfile

---

.github/workflows/release.yml
.gitignore
.goreleaser.yml
scripts/completions.sh
scripts/fury-upload.sh

ci: support building and publishing of uplift linux packages using fury

---

cmd/uplift/bump.go
cmd/uplift/changelog.go
cmd/uplift/release.go
cmd/uplift/tag.go
internal/task/gitdetect/detect.go
internal/task/gitdetect/detect_test.go

feat: git repository detection earlier in pipeline

---

docs/content/scm/about.md
docs/content/scm/gitea.md
docs/mkdocs.yml
internal/config/uplift.go
internal/context/context.go
internal/git/utils.go
internal/git/utils_test.go
internal/task/scm/scm.go
internal/task/scm/scm_test.go

feat: add scm detection support for gitea

---

docs/content/install.md

docs: include install options for linux packages

---

.github/workflows/release.yml
.goreleaser.yml
docs/content/scm/github.md
docs/content/scm/gitlab.md
docs/mkdocs.yml
internal/config/uplift.go
internal/task/scm/scm.go
internal/task/scm/scm_test.go

feat: detect self hosted github and gitlab repositories

---

.github/workflows/ci.yml
.github/workflows/release.yml
.goreleaser.yml
internal/task/beforehook/hook.go
internal/task/beforehook/hook_test.go

fix: hooks are being executed in dry-run mode

---

cmd/uplift/bump.go
cmd/uplift/changelog.go
cmd/uplift/release.go
cmd/uplift/tag.go

feat: move the before hook after git checks to improve usability

---

internal/git/utils.go
internal/git/utils_test.go
internal/task/scm/scm.go
internal/task/scm/scm_test.go

fix: gitlab remote with nested group structure incorrectly truncated

---

docs/static/schema.json

feat: publish first draft of JSON schema for uplift configuration file

---

.github/workflows/docker-test.yml
Dockerfile

feat: install uplift within docker image using built apk

---

cmd/uplift/changelog.go
internal/config/uplift.go
internal/config/uplift_test.go
internal/git/utils.go
internal/task/gitcommit/commit.go
internal/task/gitcommit/commit_test.go
internal/task/gittag/gittag.go
internal/task/gittag/gittag_test.go

feat: git push options are independently supported for both branch and tag operations

---

internal/git/utils.go
internal/git/utils_test.go
internal/task/changelog/changelog.go

fix: changelog tag not being removed during dry-run

---

cmd/uplift/changelog.go
cmd/uplift/changelog_test.go
cmd/uplift/release.go
cmd/uplift/release_test.go
docs/changelog.md
docs/reference/cli/changelog.md
docs/reference/cli/release.md
docs/reference/config.md
docs/static/schema.json
internal/config/uplift.go
internal/context/context.go
internal/task/changelog/changelog.go
internal/task/changelog/changelog_test.go

feat: support skipping prerelease tags in changelog

---

cmd/uplift/tag.go
flake.lock
go.mod

feat(deps): bump version of go 1.22.5
